language: node_js
cache: yarn
sudo: required
notifications:
  email: false
node_js:
  - '8'
before_install:
  - export CHROME_BIN=chromium-browser
  - npm i -g npm@3 # fix for https://github.com/npm/npm/issues/19222
after_success:
  - yarn build:lib
  - cp .git dist/ngx-timeago/ -r # required by semantic release
  - cp README.md dist/ngx-timeago/
  - cd dist/ngx-timeago
  - yarn install
  - yarn semantic-release
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
addons:
    chrome: stable
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
