language: node_js
sudo: required
notifications:
  email: false
node_js:
  - '10'
before_install:
  - export CHROME_BIN=chromium-browser
  - if [[ `npm -v` != 6* ]]; then npm i -g npm@6; fi
after_success:
  - npm run build:lib
  - npm run build:demo
  - cp .git dist/ngx-timeago/ -r # required by semantic release
  - cp README.md dist/ngx-timeago/
  - cd dist/ngx-timeago
  - npm install
  - npm run semantic-release
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
addons:
    chrome: stable
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  local_dir: dist/demo/
  on:
    branch: master
